### ISSUE TITLE
Checklist Summary

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/the-4th-kind#7]
- [x]  Project and app created.
- [x]  Static files moved and accessible.
- [x]  Templates integrated and configured.
- [x]  URLs mapped to templates.
- [x]  Custom 404 handler implemented.

This setup should ensure all files and templates are correctly integrated and accessible.

**Comment by V-FOR-VEND3TTA** [comment]
Done and done.

NB: For the custom 404 handler, we just make the following tweaks in `settings.py`:
```
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
```
